name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  check-file:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Check for the presence of the text file
        run: |
          if [ -f "檔案A.txt" ]; then
            echo "Text file exists."
          else
            echo "Text file does not exist."
            exit 1
          fi